#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
traefik_info () {

traefik_menu_start_setup
# VARIABLES ####################################################################
pgrole="traefik"
image="traefik:1.7"
port_inside01="80"; port_outside01="80"
port_inside02="443"; port_outside02="443"

container_reset
container_rebuild treafik
rm -rf /pg/data/traefik
common_fcreate_silent /pg/data/traefik/acme

i=0
while read p; do
  if [[ "$i" == "0" ]]; then echo -n "${p}: " >> /pg/tmp/p.info
  else echo -n "          ${p}: " >> /pg/tmp/p.info; fi
  i=1
  echo $(cat "$traefik_path/$provider/$p") >> /pg/tmp/p.info
done <"$traefik_path"/provider.keys
pfillin=$(cat /pg/tmp/p.info)

# IMAGES EXPORT - 1ST IS DEFAULT ###############################################
cat <<- EOF > "/pg/images/$pgrole.images"
traefik:1.7
EOF

rm -rf /pg/data/traefik/acme/acme.json

# YML EXPORT ###################################################################
container_core
cat <<- EOF > "/pg/data/traefik/traefik.yml"
$container_header
### ALIGN WITH THE A ################################## START - EXTRAS #########

####### ALIGN WITH THE A ############################## CORE ###################
        $container_start
        published_ports:
          - '${portcheck_add}${port_outside01}:${port_inside01}'
          - '$portstatus$port_outside02:$port_inside02'
        env:
          PUID: '1000'
          PGID: '1000'
          PROVIDER: '$provider'
          $pfillin
        volumes:
          - '/pg/data/traefik/traefik.toml:/etc/traefik/traefik.toml:ro'
          - '/etc/localtime:/etc/localtime:ro'
          - '/pg/data/traefik/acme:/etc/traefik/acme'
          - '/var/run/docker.sock:/var/run/docker.sock:ro'
        state: started
        restart_policy: unless-stopped
        networks:
          - name: plexguide
            aliases:
              - 'traefik'

### ALIGN WITH THE A ################################## END - EXTRAS ###########

EOF

touch /pg/data/traefik/acme/acme.json
chmod 600 /pg/data/traefik/traefik.toml /pg/data/traefik/acme/acme.json
chown 1000 /pg/data/traefik/traefik.toml /pg/data/traefik/acme/acme.json

}
